name: Secret Processing Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-test-secret-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      env: # Set the secret as an input
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
      run: ./secret_processor.sh
